# Site settings
title:       Mariano Gappa's Blog
email:       mariano.gappa@gmail.com
author:      Mariano Gappa
description: "Blog about Software Engineering and Music Production."
baseurl:     ""
url:         "http://marianogappa.github.io"
date_format: "%b %-d, %Y"

# Google services
google_analytics: "UA-58930438-4"
google_verification:

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false
show_social_icons:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username: MarianoGappa
bitbucket_username:
stackoverflow_id:
twitter_username: MarianoGappa
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: ''
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: true
share_tumblr: true
share_reddit: true
share_stumbleupon: true
share_hackernews: true

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     999999
sass:
  compressed: true

gems: [jekyll-paginate]
